### ISSUE TITLE
Login Error with Piler 1.4.2

### ISSUE THREAD

**Issue by simatec** [patschi/mailpiler-mailcow-integration#3]
Hello,

When I roll out a Docker container and add the Mailcow integration, the login is only possible using the mail addresses from Mailcow.

If I want to log in e.g. as admin or auditor, I get an http 500 error.

Is there already a fix or workaround for this?

Here is my repo to the Docker piler
https://github.com/simatec/piler-docker

`thrown in /etc/piler/auth-mailcow.php on line 47" while reading response header from upstream, client: 192.168.75.233, server: archiv.yyy.de, request: "POST /login.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "archiv.xxxxx.de", referrer: "https://archiv.yyy.de/"
2023/01/12 13:32:13 [error] 65#65: *27 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /etc/piler/auth-mailcow.php:47
Stack trace:
#0 /var/piler/www/model/user/auth.php(132): query_mailcow_for_email_access()
https://github.com/simatec/piler-docker/issues/1 /var/piler/www/model/user/auth.php(49): ModelUserAuth->checkFallbackLogin()
https://github.com/simatec/piler-docker/issues/2 /var/piler/www/controller/login/login.php(48): ModelUserAuth->checkLogin()
#3 /var/piler/www/system/front.php(36): ControllerLoginLogin->index()
#4 /var/piler/www/system/front.php(14): Front->execute()
#5 /var/piler/www/index.php(114): Front->dispatch()
#6 {main}`

**Comment by patschi** [comment]
I've been testing Piler 1.4.1 with PHP 7.4 and it's working fine (also login using `admin@local`). I'm now upgrading my older instance from 20.04 to 22.04 and get PHP 8.1 installed for further testing.

**Comment by simatec** [comment]
in the Docker version there were unfortunately problems with 1.4.1.  Therefore it is not possible to test with it.  a test is only possible with 1.4.2.  php8.1 is running there.
