### ISSUE TITLE
Login with local accounts not possible using Mailpiler 1.4.6

### ISSUE THREAD

**Issue by ahaase-moditech** [patschi/mailpiler-mailcow-integration#4]
Hello,

I updated my Mailpiler installation to v1.4.6. Integration of auth-mailcow.php is done as documented and has not been touched. Logging in with credentials from mailcow users works as expected, but when using admin@local or audit@local with their corresponding passwords, I get the following error in error.log:

```
2024/09/30 16:50:17 [error] 1193#1193: *48 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/spool/piler/www/system/misc.php:628
Stack trace:
#0 /var/spool/piler/www/model/user/user.php(77): get_q_string()
#1 /var/spool/piler/www/model/user/auth.php(138): ModelUserUser->get_email_addresses_from_groups()
#2 /var/spool/piler/www/model/user/auth.php(49): ModelUserAuth->checkFallbackLogin()
#3 /var/spool/piler/www/controller/login/login.php(48): ModelUserAuth->checkLogin()
#4 /var/spool/piler/www/system/front.php(36): ControllerLoginLogin->index()
#5 /var/spool/piler/www/system/front.php(14): Front->execute()
#6 /var/spool/piler/www/index.php(113): Front->dispatch()
#7 {main}
  thrown in /var/spool/piler/www/system/misc.php on line 628" while reading response header from upstream, client: 10.3.10.9, server: _, request: "POST /login.php HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "mailarchive.DOMAIN", referrer: "https://mailarchive.DOMAIN/"
```

If I remove the include line of auth-mailcow.php from config-site.php, the login for the local accounts works.

How can this be fixed?

Regards,
Andreas

**Comment by ckruijntjens** [comment]
> Hello,
> 
> I updated my Mailpiler installation to v1.4.6. Integration of auth-mailcow.php is done as documented and has not been touched. Logging in with credentials from mailcow users works as expected, but when using admin@local or audit@local with their corresponding passwords, I get the following error in error.log:
> 
> ```
> 2024/09/30 16:50:17 [error] 1193#1193: *48 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/spool/piler/www/system/misc.php:628
> Stack trace:
> #0 /var/spool/piler/www/model/user/user.php(77): get_q_string()
> #1 /var/spool/piler/www/model/user/auth.php(138): ModelUserUser->get_email_addresses_from_groups()
> #2 /var/spool/piler/www/model/user/auth.php(49): ModelUserAuth->checkFallbackLogin()
> #3 /var/spool/piler/www/controller/login/login.php(48): ModelUserAuth->checkLogin()
> #4 /var/spool/piler/www/system/front.php(36): ControllerLoginLogin->index()
> #5 /var/spool/piler/www/system/front.php(14): Front->execute()
> #6 /var/spool/piler/www/index.php(113): Front->dispatch()
> #7 {main}
>   thrown in /var/spool/piler/www/system/misc.php on line 628" while reading response header from upstream, client: 10.3.10.9, server: _, request: "POST /login.php HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "mailarchive.DOMAIN", referrer: "https://mailarchive.DOMAIN/"
> ```
> 
> If I remove the include line of auth-mailcow.php from config-site.php, the login for the local accounts works.
> 
> How can this be fixed?
> 
> Regards, Andreas

I Have the same issue.

**Comment by ckruijntjens** [comment]
Not much happening here? Anybody has the same issue?

**Comment by patschi** [comment]
I'm trying to get my mailpiler instance revived and this checked ASAP. Sorry for the delay.

**Comment by ckruijntjens** [comment]
> I'm trying to get my mailpiler instance revived and this checked ASAP. Sorry for the delay.

Hi,

No problem. thanks for your effort. The latest mailpiler version with this php script and mailcow will give an error 500 with every account. (It should ask for 2fa but errors out with error 500)

**Comment by patschi** [comment]
I think I may have found the issue... 

I guess due to some changes on mailpiler-side, it triggered a small bug in my code.

Can you please try changing following:
```php
        if ($data === "") {
                return;
        }
```

to:
```php
        if ($data === "" || $username === "") {
                return [];
        }
```

And let me know if that fixes it?

**Comment by ahaase-moditech** [comment]
I can confirm, that your change fixes the problem for me. Thank you very much.

**Comment by ckruijntjens** [comment]
> I can confirm, that your change fixes the problem for me. Thank you very much.

i get no error 500 anymore however the 2fa does not work anymore.

**Comment by ckruijntjens** [comment]
so,

with the new code the local accounts are working again. However the mailcow email login is not working. it fails the 2fa

**Comment by ckruijntjens** [comment]
i can login with audit@local. Not email accounts.

and when i wanna open a message piler gives me this error

Message Failed Verification

**Comment by patschi** [comment]
I tested email accounts, it is working fine for me. But I'm not using any 2FA.

Which kind of 2FA are you using?

**Comment by ckruijntjens** [comment]
> I tested email accounts, it is working fine for me. But I'm not using any 2FA.
> 
> Which kind of 2FA are you using?

google 2fa

**Comment by patschi** [comment]
Ah, good to know this feature exists. I have enabled it:
![image](https://github.com/user-attachments/assets/cfd383fe-fc0c-4de7-ae96-214bf91da319)

And, it works for me: Login works, things like name, email addresses, etc is being updated.

**Comment by ckruijntjens** [comment]
> Ah, good to know this feature exists. I have enabled it: ![image](https://private-user-images.githubusercontent.com/2029878/386235873-cfd383fe-fc0c-4de7-ae96-214bf91da319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTUyNjIsIm5iZiI6MTczMTU5NDk2MiwicGF0aCI6Ii8yMDI5ODc4LzM4NjIzNTg3My1jZmQzODNmZS1mYzBjLTRkZTctYWU5Ni0yMTRiZjkxZGEzMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTQzNjAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDllMzIwMTJiMjk2ODUyMGNkYzM5NTA2OWEyOTZlMzcxOTQ3MGZmZjU1NGMwNTA4Zjg3Y2ExYzY1M2FiMDY1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CBYPWBagNQRynCu9kiGMtJPipvsPhGXZ2nfvpWzStrg)
> 
> And, it works for me: Login works, things like name, email addresses, etc is being updated.

ok then i have to look in my setup why its not working for me. I upgraded piler after that the problem starts. maybe i will reinstall it all. thanks for your support.

**Comment by patschi** [comment]
Should the issue persist with 2FA, please create a new issue for me. Just to track this separately. Thank you!
