### ISSUE TITLE
piler 1.4.7 cant login with mailcow accounts error 500

### ISSUE THREAD

**Issue by ckruijntjens** [patschi/mailpiler-mailcow-integration#6]
Hi,

I upgraded to piler 1.4.7 and now the script is not working anymore. Every account gives an error 500 except for the local accounts.

The error in the logs:

PHP Warning:  file_get_contents(https://192.168.2.8/api/v1/get/alias/all): Failed to open stream: operation failed in /etc/piler/auth-mailcow.php on line 141; PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/piler/www/system/misc.php:613
Stack trace:
#0 /var/piler/www/model/user/user.php(77): get_q_string()
#1 /var/piler/www/model/user/auth.php(126): ModelUserUser->get_email_addresses_from_groups()
#2 /var/piler/www/model/user/auth.php(49): ModelUserAuth->checkFallbackLogin()
#3 /var/piler/www/controller/login/login.php(48): ModelUserAuth->checkLogin()
#4 /var/piler/www/system/front.php(36): ControllerLoginLogin->index()
#5 /var/piler/www/system/front.php(14): Front->execute()
#6 /var/piler/www/index.php(113): Front->dispatch()
#7 {main}
  thrown in /var/piler/www/system/misc.php on line 613" while reading response header from upstream, client: 192.168.2.6, server: piler.ckruijntjens.local, request: "POST /login.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "192.168.2.23", referrer: "https://piler.ckruijntjens.nl/"

**Comment by ckruijntjens** [comment]
PS api key is corrent,

When i try to login with a earlier version of mailpiler it works. I am using php8.2

**Comment by ckruijntjens** [comment]
Nevermind,

With the new mailpiler these settings are not needed anymore apparantly.... Without all is working now....

#$config['MEMCACHED_ENABLED'] = 1;
#$config['MAILCOW_API_KEY'] = '*****';
#$config['MAILCOW_SET_REALNAME'] = true; // when not specified, then default is false
#$config['CUSTOM_EMAIL_QUERY_FUNCTION'] = 'query_mailcow_for_email_access';
#include('auth-mailcow.php');

**Comment by Skydiver84de** [comment]
But without the settings you do not have access to aliases or? For me 1.4.7 does not work and I get the error as described in your opening statement.
